@startuml

entity "Source Gateway G1" as sg
entity "Recipient Gateway G2" as rg
entity "Log Storage API" as log


sg->log: 1: log(init,n,k,G2)

sg->sg: <color:red><&warning> Crash <&warning>\n ... \n<color:green>recover

sg->log: obtain lastEntry(log)
sg->rg:<color:green>send rm
return current state
sg->rg: init(n,k)

@enduml